available_ids:
- chengchi1007
- chenhao1213
- dddd110
- denghaimeng
- djiangjiang
- du55148
- dusi605
- eastwangwei
- fanhuayang
- geminiyy
- gloden613
- gorgeous0912
- hsdfuieqg
- hysz0821
- jacksisi
- jcy666
- jiangshuai0210
- jinzhanbo
- jiwei313
- jjjerry12138
- jokerking1
- jufuchao
- keyongkk
- kezzymik
- liucong126
- luanjing
- ly1122
- ohyeah00
- permanentlove
- phoenixcsw01
- pycjn666
- qinghui9527
- qqmail4092
- quepimao
- roseqw
- rushly
- sinayliu
- sollasi
- starysinger
- straghtwizard
- tangjiayuan1004
- tianxianglii
- top1pcl
- uamadeus
- wenyangtang
- wzywzy1227
- xiaoluoalice
- xulijuan
- xuwenhui123
- yangjiamin
- yccwff
- ycy1n66
- yinmengmeng
- yuanhahah
- ywhicher
- yyyyjay
- zhaotianchi
- zhoujiahui0199
- zhuxinchen07
- zjl001
- zongjiaxin
exhausted_ids:
- chencaihonga
- chenrunze11
- smartchaochao
- zhikaiwang
- ssss7777
- liucong12601
- rrrrmm
- lemonlaila
- robinrainy
- zhuangminghui
- asdsad0000
- linyunlk243
- srmmmm
- autune
- asssmer
- cycyxcy
- cshlhs
- kanwenbin
- chuasiliu
- cq1234
- maoshuwen0415
- sss45633
- tangjudge
- b201xiaoli
- yangyangchengcheng
- cdong121
- fzzy123
- rmoope
- huoqiuxia
- qcx2333
- cfy002
- liucong12601
- xulin5522
- xx03071425
- tangyujie123
- rqmiraitowa
- zhuzichen123
- miratowa1
- houwen
- elong1202
- zhangtingfengztf
- zzr123123
- xwj66666
- xpeng01
- cheaterchow
sleep_time_hr: 0.0
last_supabase_id: 497
poll_interval_minutes: 10
running_nodes:
- id: ttzyty
  notebooks:
  left_time: 19.257843417222222
finished_notebooks: