available_ids:
- chenhao1213
- cq1234
- cshlhs
- djiangjiang
- du55148
- dusi605
- eastwangwei
- elong1202
- fzzy123
- geminiyy
- gloden613
- gorgeous0912
- houwen
- hsdfuieqg
- hysz0821
- jacksisi
- jcy666
- jiangshuai0210
- jiwei313
- jjjerry12138
- jufuchao
- keyongkk
- kezzymik
- lemonlaila
- liucong126
- liucong12601
- luanjing
- ly1122
- miratowa1
- ohyeah00
- permanentlove
- pycjn666
- qcx2333
- qqmail4092
- quepimao
- rmoope
- rushly
- sinayliu
- smartchaochao
- sss45633
- ssss7777
- starysinger
- straghtwizard
- tangjiayuan1004
- tangjudge
- tangyujie123
- ttzyty
- uamadeus
- wenyangtang
- wzywzy1227
- xpeng01
- xulijuan
- xulin5522
- xuwenhui123
- yangjiamin
- yccwff
- ycy1n66
- yinmengmeng
- yuanhahah
- ywhicher
- yyyyjay
- zhaotianchi
- zhoujiahui0199
- zhuangminghui
- zhuzichen123
- zjl001
exhausted_ids:
- xwj66666
- cheaterchow
- yangyangchengcheng
- chenrunze11
- xiaoluoalice
- jinzhanbo
- maoshuwen0415
- chuasiliu
- asdsad0000
- tianxianglii
- chengchi1007
- robinrainy
- zhuxinchen07
- qinghui9527
- zongjiaxin
- dddd110
- denghaimeng
- linyunlk243
- zhikaiwang
- cycyxcy
- asssmer
- roseqw
- kanwenbin
- rqmiraitowa
- autune
- top1pcl
- zhangtingfengztf
- rrrrmm
- cdong121
- b201xiaoli
- cfy002
- srmmmm
sleep_time_hr: 0.0
last_supabase_id: 497
poll_interval_minutes: 10
running_nodes:
- id: sollasi
  notebooks:
  - kernel_id: sollasi/first-cam-depth232-s42-mt-dcw2c-mf1-msl9-r6
    memo: seed:42; model.loop:True; model.simple_camera:True; data.pose_convention:w2c;
      optim.warmup_epochs:-1; model.rope_freq:-1; model.grad_start_layer:9; postprocess.val.metrics.recon.from_depth_err:True;
      data.data_module.train_config.batch_size:80; model.enable_point:False; postprocess.train.transform.global_from_depth:True
    run_id: 6
    total_runs: 10
    start_time: '2026-07-23 05:26:59'
    resumed_from: sollasi/first-cam-depth232-s42-mt-dcw2c-mf1-msl9-r5
    history_ids:
    - zhikaiwang/first-cam-depth232-s42-mt-dcw2c-mf1-msl9-r0
    - zhikaiwang/first-cam-depth232-s42-mt-dcw2c-mf1-msl9-r1
    - roseqw/first-cam-depth232-s42-mt-dcw2c-mf1-msl9-r2
    - top1pcl/first-cam-depth232-s42-mt-dcw2c-mf1-msl9-r3
    - top1pcl/first-cam-depth232-s42-mt-dcw2c-mf1-msl9-r4
    git_branch: omega
  - kernel_id: sollasi/first-cam-depth777-s42-mt-dcw2c-mf1-msl9-r6
    memo: seed:42; model.loop:True; model.simple_camera:True; data.pose_convention:w2c;
      optim.warmup_epochs:-1; model.rope_freq:-1; model.grad_start_layer:9; postprocess.val.metrics.recon.from_depth_err:True;
      data.data_module.train_config.batch_size:80; model.enable_point:False; postprocess.train.transform.global_from_depth:False;
      postprocess.train.normalize.gt_depth.enabled:True
    run_id: 6
    total_runs: 10
    start_time: '2026-07-23 05:16:32'
    resumed_from: sollasi/first-cam-depth777-s42-mt-dcw2c-mf1-msl9-r5
    history_ids:
    - linyunlk243/first-cam-depth777-s42-mt-dcw2c-mf1-msl9-r0
    - cycyxcy/first-cam-depth777-s42-mt-dcw2c-mf1-msl9-r1
    - rqmiraitowa/first-cam-depth777-s42-mt-dcw2c-mf1-msl9-r2
    - zhangtingfengztf/first-cam-depth777-s42-mt-dcw2c-mf1-msl9-r3
    - zhangtingfengztf/first-cam-depth777-s42-mt-dcw2c-mf1-msl9-r4
    git_branch: omega
  left_time: 6.780089198611112
- id: jokerking1
  notebooks:
  - kernel_id: jokerking1/first-cam-depth394-s42-mt-dcc2w-mf1-msl9-r6
    memo: seed:42; model.loop:True; model.simple_camera:True; data.pose_convention:c2w;
      optim.warmup_epochs:-1; model.rope_freq:-1; model.grad_start_layer:9; postprocess.val.metrics.recon.from_depth_err:True;
      data.data_module.train_config.batch_size:80; model.enable_point:False; postprocess.train.transform.global_from_depth:False;
      postprocess.train.normalize.gt_depth.enabled:True
    run_id: 6
    total_runs: 10
    start_time: '2026-07-23 04:45:01'
    resumed_from: jokerking1/first-cam-depth394-s42-mt-dcc2w-mf1-msl9-r5
    history_ids:
    - asssmer/first-cam-depth394-s42-mt-dcc2w-mf1-msl9-r0
    - asssmer/first-cam-depth394-s42-mt-dcc2w-mf1-msl9-r1
    - roseqw/first-cam-depth394-s42-mt-dcc2w-mf1-msl9-r2
    - top1pcl/first-cam-depth394-s42-mt-dcc2w-mf1-msl9-r3
    - top1pcl/first-cam-depth394-s42-mt-dcc2w-mf1-msl9-r4
    git_branch: omega
  - kernel_id: jokerking1/first-cam-depth699-s42-mt-dcc2w-mf1-msl9-r6
    memo: seed:42; model.loop:True; model.simple_camera:True; data.pose_convention:c2w;
      optim.warmup_epochs:-1; model.rope_freq:-1; model.grad_start_layer:9; postprocess.val.metrics.recon.from_depth_err:True;
      data.data_module.train_config.batch_size:80; model.enable_point:False; postprocess.train.transform.global_from_depth:True;
      postprocess.train.normalize.gt_depth.enabled:True; postprocess.train.normalize.pose_translation.gt_enabled:True
    run_id: 6
    total_runs: 10
    start_time: '2026-07-23 04:45:08'
    resumed_from: jokerking1/first-cam-depth699-s42-mt-dcc2w-mf1-msl9-r5
    history_ids:
    - asssmer/first-cam-depth699-s42-mt-dcc2w-mf1-msl9-r0
    - asssmer/first-cam-depth699-s42-mt-dcc2w-mf1-msl9-r1
    - rqmiraitowa/first-cam-depth699-s42-mt-dcc2w-mf1-msl9-r2
    - zhangtingfengztf/first-cam-depth699-s42-mt-dcc2w-mf1-msl9-r3
    - zhangtingfengztf/first-cam-depth699-s42-mt-dcc2w-mf1-msl9-r4
    git_branch: omega
  left_time: 8.35332930277778
- id: zzr123123
  notebooks:
  - kernel_id: zzr123123/first-cam-depth363-s42-mf-dcc2w-mf1-msl9-r4
    memo: seed:42; model.loop:False; model.simple_camera:True; data.pose_convention:c2w;
      optim.warmup_epochs:-1; model.rope_freq:-1; model.grad_start_layer:9; postprocess.val.metrics.recon.from_depth_err:True;
      data.data_module.train_config.batch_size:80; model.enable_point:False; postprocess.train.transform.global_from_depth:True;
      postprocess.train.normalize.gt_depth.enabled:True; postprocess.train.normalize.pose_translation.gt_enabled:True
    run_id: 4
    total_runs: 10
    start_time: '2026-07-23 05:27:12'
    resumed_from: zzr123123/first-cam-depth363-s42-mf-dcc2w-mf1-msl9-r3
    history_ids:
    - kanwenbin/first-cam-depth363-s42-mf-dcc2w-mf1-msl9-r0
    - rrrrmm/first-cam-depth363-s42-mf-dcc2w-mf1-msl9-r1
    - rrrrmm/first-cam-depth363-s42-mf-dcc2w-mf1-msl9-r2
    git_branch: omega
  - kernel_id: zzr123123/first-cam-depth002-s42-mt-dcc2w-mf1-msl9-r4
    memo: seed:42; model.loop:True; model.simple_camera:True; data.pose_convention:c2w;
      optim.warmup_epochs:-1; model.rope_freq:-1; model.grad_start_layer:9; postprocess.val.metrics.recon.from_depth_err:True;
      data.data_module.train_config.batch_size:80; model.enable_point:False; postprocess.train.transform.global_from_depth:True;
      postprocess.train.normalize.gt_depth.enabled:True; postprocess.train.normalize.pose_translation.gt_enabled:True
    run_id: 4
    total_runs: 10
    start_time: '2026-07-23 06:19:45'
    resumed_from: zzr123123/first-cam-depth002-s42-mt-dcc2w-mf1-msl9-r3
    history_ids:
    - kanwenbin/first-cam-depth002-s42-mt-dcc2w-mf1-msl9-r0
    - rrrrmm/first-cam-depth002-s42-mt-dcc2w-mf1-msl9-r1
    - rrrrmm/first-cam-depth002-s42-mt-dcc2w-mf1-msl9-r2
    git_branch: omega
  left_time: 6.944376835277774
- id: phoenixcsw01
  notebooks:
  - kernel_id: phoenixcsw01/first-cam-depth144-s42-mt-dcc2w-mf1-msl9-r3
    memo: seed:42; model.loop:True; model.simple_camera:True; data.pose_convention:c2w;
      optim.warmup_epochs:-1; model.rope_freq:-1; model.grad_start_layer:9; model.grad_end_layer:3;
      postprocess.val.metrics.recon.from_depth_err:True; data.data_module.train_config.batch_size:80;
      model.enable_point:False; postprocess.train.transform.global_from_depth:True;
      postprocess.train.normalize.gt_depth.enabled:True; postprocess.train.normalize.pose_translation.gt_enabled:True;
      model.register_attention_block_indices:[1, 3, 5, 7, 9, 11]
    run_id: 3
    total_runs: 10
    start_time: '2026-07-23 05:48:19'
    resumed_from: phoenixcsw01/first-cam-depth144-s42-mt-dcc2w-mf1-msl9-r2
    history_ids:
    - b201xiaoli/first-cam-depth144-s42-mt-dcc2w-mf1-msl9-r0
    - b201xiaoli/first-cam-depth144-s42-mt-dcc2w-mf1-msl9-r1
    git_branch: omega
  - kernel_id: phoenixcsw01/first-cam-depth803-s42-mt-dcc2w-mf1-msl6-r3
    memo: seed:42; model.loop:True; model.simple_camera:True; data.pose_convention:c2w;
      optim.warmup_epochs:-1; model.rope_freq:-1; model.grad_start_layer:6; model.grad_end_layer:3;
      postprocess.val.metrics.recon.from_depth_err:True; data.data_module.train_config.batch_size:80;
      model.enable_point:False; postprocess.train.transform.global_from_depth:True;
      postprocess.train.normalize.gt_depth.enabled:True; postprocess.train.normalize.pose_translation.gt_enabled:True;
      model.register_attention_block_indices:[1, 3, 5, 7, 9, 11]; model.depth:6
    run_id: 3
    total_runs: 10
    start_time: '2026-07-23 07:01:57'
    resumed_from: phoenixcsw01/first-cam-depth803-s42-mt-dcc2w-mf1-msl6-r2
    history_ids:
    - cdong121/first-cam-depth803-s42-mt-dcc2w-mf1-msl6-r0
    - cdong121/first-cam-depth803-s42-mt-dcc2w-mf1-msl6-r1
    git_branch: omega
  left_time: 7.287184640833333
- id: xx03071425
  notebooks:
  - kernel_id: xx03071425/first-cam-depth990-s42-mt-dcc2w-mf1-msl0-r3
    memo: seed:42; model.loop:True; model.simple_camera:True; data.pose_convention:c2w;
      optim.warmup_epochs:-1; model.rope_freq:-1; model.grad_start_layer:0; postprocess.val.metrics.recon.from_depth_err:True;
      data.data_module.train_config.batch_size:80; model.enable_point:False; postprocess.train.transform.global_from_depth:True;
      postprocess.train.normalize.gt_depth.enabled:True; postprocess.train.normalize.pose_translation.gt_enabled:True;
      model.register_attention_block_indices:[1, 3, 5, 7, 9, 11]; model.depth:6
    run_id: 3
    total_runs: 10
    start_time: '2026-07-23 06:40:54'
    resumed_from: xx03071425/first-cam-depth990-s42-mt-dcc2w-mf1-msl0-r2
    history_ids:
    - cdong121/first-cam-depth990-s42-mt-dcc2w-mf1-msl0-r0
    - cdong121/first-cam-depth990-s42-mt-dcc2w-mf1-msl0-r1
    git_branch: omega
  - kernel_id: xx03071425/first-cam-depth506-s42-mt-dcc2w-mf1-msl9-r3
    memo: seed:42; model.loop:True; model.simple_camera:True; data.pose_convention:c2w;
      optim.warmup_epochs:-1; model.rope_freq:-1; model.grad_start_layer:9; model.grad_end_layer:-1;
      postprocess.val.metrics.recon.from_depth_err:True; data.data_module.train_config.batch_size:80;
      model.enable_point:False; postprocess.train.transform.global_from_depth:True;
      postprocess.train.normalize.gt_depth.enabled:True; postprocess.train.normalize.pose_translation.gt_enabled:True;
      model.register_attention_block_indices:[1, 3, 5, 7, 9, 11]
    run_id: 3
    total_runs: 10
    start_time: '2026-07-23 07:12:38'
    resumed_from: xx03071425/first-cam-depth506-s42-mt-dcc2w-mf1-msl9-r2
    history_ids:
    - b201xiaoli/first-cam-depth506-s42-mt-dcc2w-mf1-msl9-r0
    - b201xiaoli/first-cam-depth506-s42-mt-dcc2w-mf1-msl9-r1
    git_branch: omega
  left_time: 6.935181269999999
- id: fanhuayang
  notebooks:
  - kernel_id: fanhuayang/first-cam-depth749-s42-mt-dcc2w-mf100-msl5-r3
    memo: seed:42; model.loop:True; model.simple_camera:True; data.pose_convention:c2w;
      optim.warmup_epochs:-1; model.rope_freq:100; model.grad_start_layer:5; model.grad_end_layer:3;
      postprocess.val.metrics.recon.from_depth_err:True; data.data_module.train_config.batch_size:80;
      model.enable_point:False; postprocess.train.transform.global_from_depth:True;
      postprocess.train.normalize.gt_depth.enabled:True; postprocess.train.normalize.pose_translation.gt_enabled:True;
      model.register_attention_block_indices:[1, 3, 5, 7, 9, 11]; model.depth:6
    run_id: 3
    total_runs: 10
    start_time: '2026-07-23 07:02:06'
    resumed_from: fanhuayang/first-cam-depth749-s42-mt-dcc2w-mf100-msl5-r2
    history_ids:
    - cfy002/first-cam-depth749-s42-mt-dcc2w-mf100-msl5-r0
    - cfy002/first-cam-depth749-s42-mt-dcc2w-mf100-msl5-r1
    git_branch: omega
  - kernel_id: fanhuayang/first-cam-depth179-s42-mt-dcc2w-mf1-msl3-r3
    memo: seed:42; model.loop:True; model.simple_camera:True; data.pose_convention:c2w;
      optim.warmup_epochs:-1; model.rope_freq:-1; model.grad_start_layer:3; model.grad_end_layer:-1;
      postprocess.val.metrics.recon.from_depth_err:True; data.data_module.train_config.batch_size:80;
      model.enable_point:False; postprocess.train.transform.global_from_depth:True;
      postprocess.train.normalize.gt_depth.enabled:True; postprocess.train.normalize.pose_translation.gt_enabled:True;
      model.register_attention_block_indices:[1, 3, 5, 7, 9, 11]; model.depth:6
    run_id: 3
    total_runs: 10
    start_time: '2026-07-23 06:51:31'
    resumed_from: fanhuayang/first-cam-depth179-s42-mt-dcc2w-mf1-msl3-r2
    history_ids:
    - cfy002/first-cam-depth179-s42-mt-dcc2w-mf1-msl3-r0
    - cfy002/first-cam-depth179-s42-mt-dcc2w-mf1-msl3-r1
    git_branch: omega
  left_time: 7.2884083199999985
- id: huoqiuxia
  notebooks:
  - kernel_id: huoqiuxia/first-cam-depth253-s42-mf-dcc2w-mf100-msl9-r4
    memo: seed:42; model.loop:False; model.simple_camera:True; data.pose_convention:c2w;
      optim.warmup_epochs:-1; model.rope_freq:100; model.grad_start_layer:9; postprocess.val.metrics.recon.from_depth_err:True;
      data.data_module.train_config.batch_size:80; model.enable_point:False; postprocess.train.transform.global_from_depth:True;
      postprocess.train.normalize.gt_depth.enabled:True; postprocess.train.normalize.pose_translation.gt_enabled:True
    run_id: 4
    total_runs: 10
    start_time: '2026-07-23 05:37:34'
    resumed_from: srmmmm/first-cam-depth253-s42-mf-dcc2w-mf100-msl9-r3
    history_ids:
    - autune/first-cam-depth253-s42-mf-dcc2w-mf100-msl9-r0
    - autune/first-cam-depth253-s42-mf-dcc2w-mf100-msl9-r1
    - srmmmm/first-cam-depth253-s42-mf-dcc2w-mf100-msl9-r2
    git_branch: omega
  - kernel_id: huoqiuxia/first-cam-depth128-s42-mt-dcc2w-mf100-msl9-r4
    memo: seed:42; model.loop:True; model.simple_camera:True; data.pose_convention:c2w;
      optim.warmup_epochs:-1; model.rope_freq:100; model.grad_start_layer:9; postprocess.val.metrics.recon.from_depth_err:True;
      data.data_module.train_config.batch_size:80; model.enable_point:False; postprocess.train.transform.global_from_depth:True;
      postprocess.train.normalize.gt_depth.enabled:True; postprocess.train.normalize.pose_translation.gt_enabled:True
    run_id: 4
    total_runs: 10
    start_time: '2026-07-23 06:40:31'
    resumed_from: srmmmm/first-cam-depth128-s42-mt-dcc2w-mf100-msl9-r3
    history_ids:
    - autune/first-cam-depth128-s42-mt-dcc2w-mf100-msl9-r0
    - autune/first-cam-depth128-s42-mt-dcc2w-mf100-msl9-r1
    - srmmmm/first-cam-depth128-s42-mt-dcc2w-mf100-msl9-r2
    git_branch: omega
  left_time: 30.0
- id: chencaihonga
  left_time: 30.0
  notebooks:
  - kernel_id: chencaihonga/first-cam-depth-pose983-s42-mt-dcc2w-mf1-msl0-r0
    memo: seed:42; model.loop:True; model.simple_camera:True; data.pose_convention:c2w;
      optim.warmup_epochs:-1; model.rope_freq:-1; model.grad_start_layer:0; model.grad_end_layer:-1;
      postprocess.val.metrics.recon.from_depth_err:True; data.data_module.train_config.batch_size:60;
      model.enable_point:False; postprocess.train.transform.global_from_depth:True;
      postprocess.train.normalize.gt_depth.enabled:True; postprocess.train.normalize.pose_translation.gt_enabled:True;
      model.register_attention_block_indices:[1, 3, 5, 7, 9, 11]; model.depth:6
    run_id: 0
    total_runs: 10
    start_time: '2026-07-23 08:36:50'
    resumed_from: null
    history_ids: []
    git_branch: omega
  - kernel_id: chencaihonga/first-cam-depth-pose611-s42-mt-dcc2w-mf1-msl0-r0
    memo: seed:42; model.loop:True; model.simple_camera:True; data.pose_convention:c2w;
      optim.warmup_epochs:-1; model.rope_freq:-1; model.grad_start_layer:0; model.grad_end_layer:-1;
      postprocess.val.metrics.recon.from_depth_err:True; data.data_module.train_config.batch_size:60;
      model.enable_point:False; postprocess.train.transform.global_from_depth:False;
      postprocess.train.normalize.gt_depth.enabled:True; postprocess.train.normalize.pose_translation.gt_enabled:True;
      model.register_attention_block_indices:[1, 3, 5, 7, 9, 11]; model.depth:6
    run_id: 0
    total_runs: 10
    start_time: '2026-07-23 08:37:57'
    resumed_from: null
    history_ids: []
    git_branch: omega
finished_notebooks: []
